/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import com.entidades.ParametroEntidad;
import com.negocioclinicabda.ParametroBO;
import com.negocioclinicabda.RangoBO;
import javax.swing.JOptionPane;

/**
 *
 * @author le0jx
 */
public class panelAgregarRangos extends javax.swing.JPanel {
    private frmMain frame;
    private final ParametroBO parametroBO = new ParametroBO();
    private final RangoBO rangoBO = new RangoBO();
    /**
     * Creates new form panelAgregarRangos
     */
    public panelAgregarRangos(frmMain frame) {
        initComponents();
        this.frame = frame;
    }
    
    public void actualizarPanel(){
        comboBoxSexo.removeAllItems();
        comboBoxSexo.addItem("Ambos");
        comboBoxSexo.addItem("Masculino");
        comboBoxSexo.addItem("Femenino");
        comboBoxSexo.setSelectedIndex(0);
        
        txtEdadFin.setText("");
        txtEdadInicio.setText("");
        txtRangoFin.setText("");
        txtRangoInicio.setText("");
        
        comboBoxParametro.removeAllItems();
        for (ParametroEntidad parametro : parametroBO.obtenerListaParametros()) {
            comboBoxParametro.addItem(new panelAgregarRangos.ComboItem(parametro.getIdParametro(), parametro.getNombre()));
        }
        
        if(comboBoxParametro.getItemCount() > 0) {
            comboBoxParametro.setSelectedIndex(0);
        }
    }
    
    private void guardarDatos() {
        try {
            String sexo = comboBoxSexo.getSelectedItem().toString();
            int edadIni = Integer.parseInt(txtEdadInicio.getText());
            int edadFin = Integer.parseInt(txtEdadFin.getText());
            double rangoIni = Double.parseDouble(txtRangoInicio.getText());
            double rangoFin = Double.parseDouble(txtRangoFin.getText());
            
            ComboItem item = (ComboItem) comboBoxParametro.getSelectedItem();
            if (item == null) {
                JOptionPane.showMessageDialog(this, "Debe registrar un parámetro primero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int idParametro = item.getId();

            boolean exito = rangoBO.registrarRango(sexo, edadIni, edadFin, rangoIni, rangoFin, idParametro);

            if (exito) {
                JOptionPane.showMessageDialog(this, "¡Rango registrado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                txtEdadInicio.setText("");
                txtEdadFin.setText("");
                txtRangoInicio.setText("");
                txtRangoFin.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el rango.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Revisa los campos numéricos (Edad y Valores).", "Error de Formato", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private class ComboItem {
        private int id;
        private String nombre;

        public ComboItem(int id, String nombre) {
            this.id = id;
            this.nombre = nombre;
        }

        public int getId() { return id; }

        @Override
        public String toString() {
            return nombre; 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxSexo = new javax.swing.JComboBox<>();
        txtEdadInicio = new javax.swing.JTextField();
        txtEdadFin = new javax.swing.JTextField();
        txtRangoInicio = new javax.swing.JTextField();
        txtRangoFin = new javax.swing.JTextField();
        comboBoxParametro = new javax.swing.JComboBox<>();
        btnGuarda = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(638, 508));
        setMinimumSize(new java.awt.Dimension(638, 508));

        jLabel1.setText("sexo:");

        jLabel2.setText("edad inicial:");

        jLabel3.setText("edad final:");

        jLabel4.setText("valor minimo:");

        jLabel5.setText("valor maximo:");

        jLabel6.setText("parametro:");

        new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino," });
        comboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSexoActionPerformed(evt);
            }
        });

        btnGuarda.setText("guardar");
        btnGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaActionPerformed(evt);
            }
        });

        btnCancelar.setText("cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEdadInicio)
                            .addComponent(txtEdadFin)
                            .addComponent(txtRangoInicio)
                            .addComponent(txtRangoFin)
                            .addComponent(comboBoxParametro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnGuarda)
                        .addGap(207, 207, 207))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEdadInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdadFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRangoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRangoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuarda)
                    .addComponent(btnCancelar))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        frame.mostrarPanel("analisis");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaActionPerformed
        // TODO add your handling code here:
        guardarDatos();
        frame.mostrarPanel("analisis");
    }//GEN-LAST:event_btnGuardaActionPerformed

    private void comboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSexoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuarda;
    private javax.swing.JComboBox<ComboItem> comboBoxParametro;
    private javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEdadFin;
    private javax.swing.JTextField txtEdadInicio;
    private javax.swing.JTextField txtRangoFin;
    private javax.swing.JTextField txtRangoInicio;
    // End of variables declaration//GEN-END:variables
}
