/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import com.entidades.ServicioAnalisisEntidad;
import com.negocioclinicabda.ServicioAnalisisBO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author le0jx
 */
public class panelServiciosAnalisis extends javax.swing.JPanel {
    private frmMain frame;
    private final ServicioAnalisisBO analisisBO = new ServicioAnalisisBO();
    
    /**
     * Creates new form panelServiciosAnalisis
     */
    public panelServiciosAnalisis(frmMain frame) {
        initComponents();
        this.frame = frame;
        actualizarPanel();
    }
    
    public void actualizarPanel(){
        DefaultTableModel modelo = (DefaultTableModel) tablaServiciosAnalisis.getModel();
        modelo.setRowCount(0);
        List<ServicioAnalisisEntidad> analisisLista = analisisBO.obtenerTodosLosAnalisis();
        if(!analisisLista.isEmpty()){
        for (ServicioAnalisisEntidad analisis : analisisLista) {
            Object[] fila = {
                analisis.getIdAnalisis(),
                analisis.getNombre(),
                analisis.getDescripcion(),
                analisis.getMuestra().getNombre()
            };
            modelo.addRow(fila);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSolicitudes = new javax.swing.JButton();
        btnAnlaisis = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServiciosAnalisis = new javax.swing.JTable();
        btnAgregarAnalisis = new javax.swing.JButton();
        btnAgregarParametro = new javax.swing.JButton();
        btnAgregarRango = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(638, 508));
        setMinimumSize(new java.awt.Dimension(638, 508));

        jLabel1.setText("catalogo analisis");

        btnSolicitudes.setText("solicitudes");
        btnSolicitudes.setMaximumSize(new java.awt.Dimension(84, 23));
        btnSolicitudes.setMinimumSize(new java.awt.Dimension(84, 23));
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });

        btnAnlaisis.setText("analisis");
        btnAnlaisis.setEnabled(false);
        btnAnlaisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnlaisisActionPerformed(evt);
            }
        });

        btnResultados.setText("resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        tablaServiciosAnalisis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "descripcion", "muestra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaServiciosAnalisis);

        btnAgregarAnalisis.setText("agregar analisis");
        btnAgregarAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAnalisisActionPerformed(evt);
            }
        });

        btnAgregarParametro.setText("agregar parametro");
        btnAgregarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarParametroActionPerformed(evt);
            }
        });

        btnAgregarRango.setText("agregar rango");
        btnAgregarRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRangoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnlaisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnAgregarAnalisis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarParametro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarRango))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnlaisis, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarAnalisis)
                    .addComponent(btnAgregarParametro)
                    .addComponent(btnAgregarRango))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
        // TODO add your handling code here:
        frame.mostrarPanel("solicitud");
    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void btnAnlaisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnlaisisActionPerformed
        // TODO add your handling code here:
        frame.mostrarPanel("analisis");
    }//GEN-LAST:event_btnAnlaisisActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
        frame.mostrarPanel("resultados");
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnAgregarAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnalisisActionPerformed
        // TODO add your handling code here:
        frame.mostrarPanel("agregarAnalisis");
    }//GEN-LAST:event_btnAgregarAnalisisActionPerformed

    private void btnAgregarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarParametroActionPerformed
        // TODO add your handling code here:
        frame.mostrarPanel("agregarParametros");
    }//GEN-LAST:event_btnAgregarParametroActionPerformed

    private void btnAgregarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRangoActionPerformed
        // TODO add your handling code here:
        frame.mostrarPanel("agregarRangos");
    }//GEN-LAST:event_btnAgregarRangoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAnalisis;
    private javax.swing.JButton btnAgregarParametro;
    private javax.swing.JButton btnAgregarRango;
    private javax.swing.JButton btnAnlaisis;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaServiciosAnalisis;
    // End of variables declaration//GEN-END:variables
}
